#! /bin/bash

IP_IOTRONIC="localhost"
IOTRONIC_PASS="s4t"

openstack service create iot --name Iotronic
openstack user create --password $IOTRONIC_PASS iotronic
openstack role add --project service --user iotronic admin
openstack role create admin_iot_project
openstack role create manager_iot_project
openstack role create user_iot
openstack role add --project service --user iotronic admin_iot_project

openstack endpoint create --region RegionOne iot public http://$IP_IOTRONIC:8812
openstack endpoint create --region RegionOne iot internal http://$IP_IOTRONIC:8812
openstack endpoint create --region RegionOne iot admin http://$IP_IOTRONIC:8812

openstack role add --project admin --user admin admin_iot_project
